### ISSUE TITLE
struggling to get data with timemachine

### ISSUE THREAD

**Issue by bzigterman** [alexander0042/pirateweather#18]
I'm having trouble getting data from the timemachine API, and I'm not sure what I'm doing wrong. 

Here's my API request: `https://timemachine.pirateweather.net/forecast/<API_Key>/40,-88,-86400` to get the weather results for the past day.
And here's the response: `"Data for this date is not yet available, please try an earlier or later date"`

I've also tried various unix timestamps from the past week and few months, but I continue to get the same result.

Right now, I'm just trying this out in my web browser, but I would like to eventually use this with R in RStudio. There I'm getting a `500` error code and the same message.

Am I misunderstanding what the timemachine API is for or what timeframes should be available?

Any help or suggestions would be appreciated!

**Comment by bzigterman** [comment]
Ah, that all makes sense. I guess I just needed to be more patient for the timemachine documentation. Thanks!

**Comment by bizzinho** [comment]
How _does_ one query the timemachine end point? Probably it's just my ignorance, but I haven't been able to get anything but `"Data for this date is not yet available, please try an earlier or later date"` regardless of the location and time deltas I've tried.

**Comment by Ker-ple** [comment]
It seems that timemachine is having problems - any date more recent than June 30th, 2022 returns "Data for this date is not yet available, please try an earlier or later date."

**Comment by alexander0042** [comment]
Thanks for alerting me to this, and apologies for the slow response on my part! It seems to be a bug with how the datetime gets filtered, so I'll investigate and report back

**Comment by cloneofghosts** [comment]
@alexander0042 When you query with a UNIX timestamp it also allows you to do queries for times in the future as long as there is data available for that timestamp you are using. Not sure if that's intended or known behaviour so not sure if that's something you need to fix.

**Comment by alexander0042** [comment]
Ok, dug into this on the weekend and I think I have everything working:
- Dates up until ~1 month ago are returning data, and should keep moving forward as data becomes available. Times in the future don't return data, as expected
- Data in the currently block is fixed
- Integers are integered, floats are rounded to 2 decimal points
- Text descriptions are now much better

**Comment by cloneofghosts** [comment]
@alexander0042 Can confirm that February is returning data. There's a few spots you missed in your last round of fixes:

`longitude` and `moonPhase` aren't rounded (maybe `latitude` as well) and the `summary` on currently was missed as well.

**Comment by alexander0042** [comment]
Great catches- should all be in there now!

**Comment by cloneofghosts** [comment]
@alexander0042 The `icon` and `summary` are switched in the currently block. `icon` is showing the `summary` and `summary` is showing the `icon`

**Comment by alexander0042** [comment]
I saw that right after I posted☔ Just waiting for the update to propagate, but should be fixed shortly

**Comment by cloneofghosts** [comment]
Just checked and everything is working correctly now.

**Comment by cloneofghosts** [comment]
Closing this one for cleanup. If you come across this issue in the future feel free to re-open or create another issue.
